version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres:/var/lib/postgresql/data
